// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnica.Repositories;

namespace PruebaTecnica.Migrations
{
    [DbContext(typeof(AwesomeNetDBContext))]
    partial class AwesomeNetDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("PruebaTecnica.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeWorld")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2021, 5, 31, 21, 34, 54, 228, DateTimeKind.Utc).AddTicks(6806),
                            Edited = new DateTime(2021, 5, 31, 21, 34, 54, 228, DateTimeKind.Utc).AddTicks(7065),
                            Height = 172,
                            HomeWorld = "Tatooine",
                            Name = "Luke Skywalker",
                            Specie = "Human"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2021, 5, 31, 21, 34, 54, 228, DateTimeKind.Utc).AddTicks(7324),
                            Edited = new DateTime(2021, 5, 31, 21, 34, 54, 228, DateTimeKind.Utc).AddTicks(7336),
                            Height = 167,
                            HomeWorld = "Tatooine",
                            Name = "C-3PO",
                            Specie = "Droid"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2021, 5, 31, 21, 34, 54, 228, DateTimeKind.Utc).AddTicks(7342),
                            Edited = new DateTime(2021, 5, 31, 21, 34, 54, 228, DateTimeKind.Utc).AddTicks(7343),
                            Height = 150,
                            HomeWorld = "Alderaan",
                            Name = "Leia Organa",
                            Specie = "Human"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
